default: &default
  bootstrap_servers: <%= ENV['BOOTSTRAP_SERVERS'] || 'localhost:9092' %>
  security_protocol: <%= ENV['SECURITY_PROTOCOL'] %>
  sasl_mechanism: <%= ENV['SASL_MECHANISM'] %>
  sasl_username: <%= ENV['SASL_USERNAME'] %>
  sasl_password: <%= ENV['SASL_PASSWORD'] %>
  topics:
    - customer_created
    - customer_deleted
    - customer_updated
    - organization_created
    - organization_updated
    - organization_deleted

test:
  <<: *default
  bootstrap_servers: 'localhost:9092'

development:
  <<: *default

production:
  <<: *default
